// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: partition.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Partition_Split_FullMethodName = "/partition.Partition/split"
)

// PartitionClient is the client API for Partition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartitionClient interface {
	Split(ctx context.Context, in *File, opts ...grpc.CallOption) (*FilePartition, error)
}

type partitionClient struct {
	cc grpc.ClientConnInterface
}

func NewPartitionClient(cc grpc.ClientConnInterface) PartitionClient {
	return &partitionClient{cc}
}

func (c *partitionClient) Split(ctx context.Context, in *File, opts ...grpc.CallOption) (*FilePartition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilePartition)
	err := c.cc.Invoke(ctx, Partition_Split_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartitionServer is the server API for Partition service.
// All implementations must embed UnimplementedPartitionServer
// for forward compatibility.
type PartitionServer interface {
	Split(context.Context, *File) (*FilePartition, error)
	mustEmbedUnimplementedPartitionServer()
}

// UnimplementedPartitionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartitionServer struct{}

func (UnimplementedPartitionServer) Split(context.Context, *File) (*FilePartition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Split not implemented")
}
func (UnimplementedPartitionServer) mustEmbedUnimplementedPartitionServer() {}
func (UnimplementedPartitionServer) testEmbeddedByValue()                   {}

// UnsafePartitionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartitionServer will
// result in compilation errors.
type UnsafePartitionServer interface {
	mustEmbedUnimplementedPartitionServer()
}

func RegisterPartitionServer(s grpc.ServiceRegistrar, srv PartitionServer) {
	// If the following call pancis, it indicates UnimplementedPartitionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Partition_ServiceDesc, srv)
}

func _Partition_Split_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionServer).Split(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Partition_Split_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionServer).Split(ctx, req.(*File))
	}
	return interceptor(ctx, in, info, handler)
}

// Partition_ServiceDesc is the grpc.ServiceDesc for Partition service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Partition_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "partition.Partition",
	HandlerType: (*PartitionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "split",
			Handler:    _Partition_Split_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "partition.proto",
}
